version : '3'
services:
  dm-web:
    image: dm/dm-platform
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis-server
    container_name: dm-platform
    restart: always
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker_v/mysql/conf.d:/etc/mysql/conf.d
      - /data/mysql/data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=15298382837LIUxia_
    container_name: mysql
    restart: always

  redis-server:
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - /data:/data
    container_name: redis-server
    restart: always