INSERT INTO data_mining.data_set_collection (collectionId, abstractInfo, collectionName, dataDonated, description, isMissingValues, hits, relevantPapers, topics, areaId) VALUES ('402881e85ec408fc015ec85a2c3a001d', 'For Further information about the variables see the file in the data folder.', 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet Data Set ', '2017-09-28', null, 'true', 2131, 'Liang, X., S. Li, S. Zhang, H. Huang, and S. X. Chen (2016), PM2.5 data reliability, consistency, and air quality assessment in five Chinese cities, J. Geophys. Res. Atmos., 121, 10220â€“10236, [Web Link].

', null, 0);
INSERT INTO data_mining.data_set_collection (collectionId, abstractInfo, collectionName, dataDonated, description, isMissingValues, hits, relevantPapers, topics, areaId) VALUES ('402881e85ec408fc015ec86463000021', 'Prof. D. Petkovic (SFSU) Petkovic ''@'' sfsu.edu; Prof. Rainer Todtenhoefer (Fulda University, Germany); Prof. Shihong Huang (FAU)', 'Data for Software Engineering Teamwork Assessment in Education Setting Data Set ', '2017-09-28', null, 'true', 0, 'Liang, X., S. Li, S. Zhang, H. Huang, and S. X. Chen (2016), PM2.5 data reliability, consistency, and air quality assessment in five Chinese cities, J. Geophys. Res. Atmos., 121, 10220â€“10236, [Web Link].

', null, 0);
INSERT INTO data_mining.data_set_collection (collectionId, abstractInfo, collectionName, dataDonated, description, isMissingValues, hits, relevantPapers, topics, areaId) VALUES ('402881e85ec99a00015ecb05dd7e0002', '', 'DAADA', '2017-09-29', null, null, 0, null, null, null);
INSERT INTO data_mining.data_set_collection (collectionId, abstractInfo, collectionName, dataDonated, description, isMissingValues, hits, relevantPapers, topics, areaId) VALUES ('402881ef5ecb1bf1015ecb3285000003', 'For Further information about the variables see the file in the data folder.', 'Parkinson Disease Spiral Drawings Using Digitized ', '2017-09-29', null, 'true', 0, 'Liang, X., S. Li, S. Zhang, H. Huang, and S. X. Chen (2016), PM2.5 data reliability, consistency, and air quality assessment in five Chinese cities, J. Geophys. Res. Atmos., 121, 10220â€“10236, [Web Link].

', null, 0);
INSERT INTO data_mining.data_set_collection (collectionId, abstractInfo, collectionName, dataDonated, description, isMissingValues, hits, relevantPapers, topics, areaId) VALUES ('8ae483f15ec86a01015ec8714a760008', 'For Further information about the variables see the file in the data folder.', 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet Data Set ', '2017-09-28', null, 'true', 0, 'Liang, X., S. Li, S. Zhang, H. Huang, and S. X. Chen (2016), PM2.5 data reliability, consistency, and air quality assessment in five Chinese cities, J. Geophys. Res. Atmos., 121, 10220â€“10236, [Web Link].

', null, 0);
INSERT INTO data_mining.data_set_collection (collectionId, abstractInfo, collectionName, dataDonated, description, isMissingValues, hits, relevantPapers, topics, areaId) VALUES ('8ae483f15ec86a01015ec873eb62000e', 'For Further information about the variables see the file in the data folder.', 'Balance Scale Data Set ', '2017-09-28', null, 'true', 0, 'Liang, X., S. Li, S. Zhang, H. Huang, and S. X. Chen (2016), PM2.5 data reliability, consistency, and air quality assessment in five Chinese cities, J. Geophys. Res. Atmos., 121, 10220â€“10236, [Web Link].

', null, 0);
INSERT INTO data_mining.data_set_collection (collectionId, abstractInfo, collectionName, dataDonated, description, isMissingValues, hits, relevantPapers, topics, areaId) VALUES ('8ae483f15ec86a01015ec87784190012', 'For Further information about the variables see the file in the data folder.', 'Breast Cancer Wisconsin (Diagnostic) Data Set ', '2017-09-28', null, 'true', 0, 'Liang, X., S. Li, S. Zhang, H. Huang, and S. X. Chen (2016), PM2.5 data reliability, consistency, and air quality assessment in five Chinese cities, J. Geophys. Res. Atmos., 121, 10220â€“10236, [Web Link].

', null, 0);